// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sample P2P Trade
This is a P2P trade system.


    Schemes:
      http
    Host: hawaiyon.ml
    BasePath: /v1
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <hawaiyon@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
