// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"demo_p2p_bak/models"
)

// AddLoanCreatedCode is the HTTP code returned for type AddLoanCreated
const AddLoanCreatedCode int = 201

/*AddLoanCreated successful operation

swagger:response addLoanCreated
*/
type AddLoanCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Loan `json:"body,omitempty"`
}

// NewAddLoanCreated creates AddLoanCreated with default headers values
func NewAddLoanCreated() *AddLoanCreated {
	return &AddLoanCreated{}
}

// WithPayload adds the payload to the add loan created response
func (o *AddLoanCreated) WithPayload(payload *models.Loan) *AddLoanCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add loan created response
func (o *AddLoanCreated) SetPayload(payload *models.Loan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddLoanCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddLoanDefault error

swagger:response addLoanDefault
*/
type AddLoanDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewAddLoanDefault creates AddLoanDefault with default headers values
func NewAddLoanDefault(code int) *AddLoanDefault {
	if code <= 0 {
		code = 500
	}

	return &AddLoanDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add loan default response
func (o *AddLoanDefault) WithStatusCode(code int) *AddLoanDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add loan default response
func (o *AddLoanDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add loan default response
func (o *AddLoanDefault) WithPayload(payload *models.APIError) *AddLoanDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add loan default response
func (o *AddLoanDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddLoanDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
