// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"demo_p2p_bak/models"
)

// AddRepayCreatedCode is the HTTP code returned for type AddRepayCreated
const AddRepayCreatedCode int = 201

/*AddRepayCreated successful operation

swagger:response addRepayCreated
*/
type AddRepayCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Repayment `json:"body,omitempty"`
}

// NewAddRepayCreated creates AddRepayCreated with default headers values
func NewAddRepayCreated() *AddRepayCreated {
	return &AddRepayCreated{}
}

// WithPayload adds the payload to the add repay created response
func (o *AddRepayCreated) WithPayload(payload *models.Repayment) *AddRepayCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add repay created response
func (o *AddRepayCreated) SetPayload(payload *models.Repayment) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRepayCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AddRepayDefault error

swagger:response addRepayDefault
*/
type AddRepayDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewAddRepayDefault creates AddRepayDefault with default headers values
func NewAddRepayDefault(code int) *AddRepayDefault {
	if code <= 0 {
		code = 500
	}

	return &AddRepayDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the add repay default response
func (o *AddRepayDefault) WithStatusCode(code int) *AddRepayDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the add repay default response
func (o *AddRepayDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the add repay default response
func (o *AddRepayDefault) WithPayload(payload *models.APIError) *AddRepayDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add repay default response
func (o *AddRepayDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddRepayDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
