// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AddRepayHandlerFunc turns a function with the right signature into a add repay handler
type AddRepayHandlerFunc func(AddRepayParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddRepayHandlerFunc) Handle(params AddRepayParams) middleware.Responder {
	return fn(params)
}

// AddRepayHandler interface for that can handle valid add repay params
type AddRepayHandler interface {
	Handle(AddRepayParams) middleware.Responder
}

// NewAddRepay creates a new http.Handler for the add repay operation
func NewAddRepay(ctx *middleware.Context, handler AddRepayHandler) *AddRepay {
	return &AddRepay{Context: ctx, Handler: handler}
}

/*AddRepay swagger:route POST /repayment transaction addRepay

还款

*/
type AddRepay struct {
	Context *middleware.Context
	Handler AddRepayHandler
}

func (o *AddRepay) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddRepayParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
