// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"demo_p2p_bak/models"
)

// GetRepayByIDOKCode is the HTTP code returned for type GetRepayByIDOK
const GetRepayByIDOKCode int = 200

/*GetRepayByIDOK successful operation

swagger:response getRepayByIdOK
*/
type GetRepayByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Loan `json:"body,omitempty"`
}

// NewGetRepayByIDOK creates GetRepayByIDOK with default headers values
func NewGetRepayByIDOK() *GetRepayByIDOK {
	return &GetRepayByIDOK{}
}

// WithPayload adds the payload to the get repay by Id o k response
func (o *GetRepayByIDOK) WithPayload(payload *models.Loan) *GetRepayByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repay by Id o k response
func (o *GetRepayByIDOK) SetPayload(payload *models.Loan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRepayByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRepayByIDDefault error

swagger:response getRepayByIdDefault
*/
type GetRepayByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetRepayByIDDefault creates GetRepayByIDDefault with default headers values
func NewGetRepayByIDDefault(code int) *GetRepayByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRepayByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get repay by Id default response
func (o *GetRepayByIDDefault) WithStatusCode(code int) *GetRepayByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get repay by Id default response
func (o *GetRepayByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get repay by Id default response
func (o *GetRepayByIDDefault) WithPayload(payload *models.APIError) *GetRepayByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get repay by Id default response
func (o *GetRepayByIDDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRepayByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
