// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"demo_p2p_bak/models"
)

// GetLoanByIDOKCode is the HTTP code returned for type GetLoanByIDOK
const GetLoanByIDOKCode int = 200

/*GetLoanByIDOK successful operation

swagger:response getLoanByIdOK
*/
type GetLoanByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Loan `json:"body,omitempty"`
}

// NewGetLoanByIDOK creates GetLoanByIDOK with default headers values
func NewGetLoanByIDOK() *GetLoanByIDOK {
	return &GetLoanByIDOK{}
}

// WithPayload adds the payload to the get loan by Id o k response
func (o *GetLoanByIDOK) WithPayload(payload *models.Loan) *GetLoanByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get loan by Id o k response
func (o *GetLoanByIDOK) SetPayload(payload *models.Loan) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoanByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetLoanByIDDefault error

swagger:response getLoanByIdDefault
*/
type GetLoanByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetLoanByIDDefault creates GetLoanByIDDefault with default headers values
func NewGetLoanByIDDefault(code int) *GetLoanByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLoanByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get loan by Id default response
func (o *GetLoanByIDDefault) WithStatusCode(code int) *GetLoanByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get loan by Id default response
func (o *GetLoanByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get loan by Id default response
func (o *GetLoanByIDDefault) WithPayload(payload *models.APIError) *GetLoanByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get loan by Id default response
func (o *GetLoanByIDDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLoanByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
