// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetRepayByIDHandlerFunc turns a function with the right signature into a get repay by Id handler
type GetRepayByIDHandlerFunc func(GetRepayByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetRepayByIDHandlerFunc) Handle(params GetRepayByIDParams) middleware.Responder {
	return fn(params)
}

// GetRepayByIDHandler interface for that can handle valid get repay by Id params
type GetRepayByIDHandler interface {
	Handle(GetRepayByIDParams) middleware.Responder
}

// NewGetRepayByID creates a new http.Handler for the get repay by Id operation
func NewGetRepayByID(ctx *middleware.Context, handler GetRepayByIDHandler) *GetRepayByID {
	return &GetRepayByID{Context: ctx, Handler: handler}
}

/*GetRepayByID swagger:route GET /repayment/{transactionId} transaction getRepayById

Find repay by ID

Find repay by ID

*/
type GetRepayByID struct {
	Context *middleware.Context
	Handler GetRepayByIDHandler
}

func (o *GetRepayByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetRepayByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
