// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDebtInfoParams creates a new GetDebtInfoParams object
// with the default values initialized.
func NewGetDebtInfoParams() GetDebtInfoParams {
	var ()
	return GetDebtInfoParams{}
}

// GetDebtInfoParams contains all the bound params for the get debt info operation
// typically these are obtained from a http.Request
//
// swagger:parameters getDebtInfo
type GetDebtInfoParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*基准用户 ID
	  Required: true
	  In: query
	*/
	BaseUserID int64
	/*另外一个用户的ID
	  Required: true
	  In: query
	*/
	ToUserID int64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetDebtInfoParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qBaseUserID, qhkBaseUserID, _ := qs.GetOK("baseUserId")
	if err := o.bindBaseUserID(qBaseUserID, qhkBaseUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	qToUserID, qhkToUserID, _ := qs.GetOK("toUserId")
	if err := o.bindToUserID(qToUserID, qhkToUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetDebtInfoParams) bindBaseUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("baseUserId", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("baseUserId", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("baseUserId", "query", "int64", raw)
	}
	o.BaseUserID = value

	return nil
}

func (o *GetDebtInfoParams) bindToUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("toUserId", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("toUserId", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("toUserId", "query", "int64", raw)
	}
	o.ToUserID = value

	return nil
}
