// Code generated by go-swagger; DO NOT EDIT.

package transaction

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"demo_p2p_bak/models"
)

// GetDebtInfoOKCode is the HTTP code returned for type GetDebtInfoOK
const GetDebtInfoOKCode int = 200

/*GetDebtInfoOK successful operation

swagger:response getDebtInfoOK
*/
type GetDebtInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.Debt `json:"body,omitempty"`
}

// NewGetDebtInfoOK creates GetDebtInfoOK with default headers values
func NewGetDebtInfoOK() *GetDebtInfoOK {
	return &GetDebtInfoOK{}
}

// WithPayload adds the payload to the get debt info o k response
func (o *GetDebtInfoOK) WithPayload(payload *models.Debt) *GetDebtInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get debt info o k response
func (o *GetDebtInfoOK) SetPayload(payload *models.Debt) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDebtInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetDebtInfoDefault error

swagger:response getDebtInfoDefault
*/
type GetDebtInfoDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetDebtInfoDefault creates GetDebtInfoDefault with default headers values
func NewGetDebtInfoDefault(code int) *GetDebtInfoDefault {
	if code <= 0 {
		code = 500
	}

	return &GetDebtInfoDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get debt info default response
func (o *GetDebtInfoDefault) WithStatusCode(code int) *GetDebtInfoDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get debt info default response
func (o *GetDebtInfoDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get debt info default response
func (o *GetDebtInfoDefault) WithPayload(payload *models.APIError) *GetDebtInfoDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get debt info default response
func (o *GetDebtInfoDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDebtInfoDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
