// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// User user
// swagger:model User

type User struct {

	// balance
	// Required: true
	Balance *int64 `json:"balance"`

	// email
	Email string `json:"email,omitempty"`

	// id
	// Read Only: true
	ID int64 `json:"id,omitempty"`

	// total borrow
	// Read Only: true
	TotalBorrow int64 `json:"total_borrow,omitempty"`

	// total lend
	// Read Only: true
	TotalLend int64 `json:"total_lend,omitempty"`

	// username
	// Required: true
	Username *string `json:"username"`
}

/* polymorph User balance false */

/* polymorph User email false */

/* polymorph User id false */

/* polymorph User total_borrow false */

/* polymorph User total_lend false */

/* polymorph User username false */

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBalance(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateUsername(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *User) validateBalance(formats strfmt.Registry) error {

	if err := validate.Required("balance", "body", m.Balance); err != nil {
		return err
	}

	return nil
}

func (m *User) validateUsername(formats strfmt.Registry) error {

	if err := validate.Required("username", "body", m.Username); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *User) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *User) UnmarshalBinary(b []byte) error {
	var res User
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
